[credentials.usernames.admin]
name = "Team Member"
password = "$2b$12$VE.xZ/VW3zYl7iLsjNeKDOw4tENSeJVCMeBbJS.ljbGZn3p0OGG0."
role = "admin"

[credentials.usernames.ceo]
name = "Cindy Sharp"
password = "$2b$12$Q4X.fzrnGQnhK.CZv5FFfebcM.8B2X7TRoyBHYb5.kHONSdyv2ge."
role = "ceo"

[credentials.usernames.website_mgr]
name = "Morgan Rockwell"
password = "$2b$12$v3Df8tKSioGhQYGBuORpwuEs.OEa/Efa5Tg2sOaa1wIoiUHwV9y3i"
role = "website_manager"

[credentials.usernames.marketing_mgr]
name = "Tom Parmesan"
password = "$2b$12$uqstmvJaDPIK6.eydXMwH.Q28Tw9jgSeOJpApyGOWnzrGlQADQRkK"
role = "marketing_manager"

[cookie]
name = "streamlit_auth_cookie_v2"
key = "scaletrix"
expiry_days = 0

# -----------------------
# SQL Server connection
# -----------------------
SERVER = "DIVYANSH\\DIVYANSH_36"   
PORT = "1433"                
DATABASE = "DigitAL"         
USERNAME = "streamlit_rudra92"  
PASSWORD = "rudram#123"   
SCHEMA = "dbo"               